### ISSUE TITLE
请问如何运行代码呢？

### ISSUE THREAD

**Issue by bleakie** [AltmanD/guandan_mcc#1]
1.如何训练模型？python learner/learner.py  是训练模型么？
2. actor_n/start.sh 是做什么的呢？如何修改ip 或者port呢？

**Comment by zzl221000** [comment]
看这里 [掼蛋AI算法对抗平台使用说明](http://gameai.njupt.edu.cn/gameaicompetition/gameGD/index.html)

**Comment by AltmanD** [comment]
> 1.如何训练模型？python learner/learner.py 是训练模型么？ 2. actor_n/start.sh 是做什么的呢？如何修改ip 或者port呢？

1. 在learner容器中运行learner/start_all.sh来开始训练模型；learner.py负责接收数据、训练模型和控制模型分发，具体训练算法在learner/agents/dqn/guandan_agent.py。
2. actor_n/start.sh是用于启动数据收集端的，通常由learner/start_all.sh调用；需要修改哪方面的ip或port？代码中涉及的ip和端口比较多，需要问题更详细一些

**Comment by LYBAB2** [comment]
这里面哪些代码部分是控制扑克牌在命令行输出牌局信息的？

**Comment by juidxsrs15746** [comment]
作者你好，听说模型还没训练至收敛，请问预训练模型可以分享一份给我吗？有偿也可以，我想把它继续训练至收敛到时候也会给您发一份可以吗？我的邮箱278937623@qq.com

**Comment by AltmanD** [comment]
> 

没理解你说的‘控制扑克牌在命令行输出牌局信息’，详细说明一下？

**Comment by AltmanD** [comment]
> 这里面哪些代码部分是控制扑克牌在命令行输出牌局信息的？

没理解你说的‘控制扑克牌在命令行输出牌局信息’，详细说明一下？

**Comment by AltmanD** [comment]
> 作者你好，听说模型还没训练至收敛，请问预训练模型可以分享一份给我吗？有偿也可以，我想把它继续训练至收敛到时候也会给您发一份可以吗？我的邮箱[278937623@qq.com](mailto:278937623@qq.com)

模型肯定训到收敛了呀，只是还没有公开到这个库，后面会公开的

**Comment by slaxman** [comment]
好像没有DQNAgent这个库，能提供一份吗？我的邮箱是 3504230@qq.com, 非常感谢

**Comment by AltmanD** [comment]
> 好像没有DQNAgent这个库，能提供一份吗？我的邮箱是 [3504230@qq.com](mailto:3504230@qq.com), 非常感谢

没有用到DQNAgent，相关代码可以注释掉

**Comment by gj78556** [comment]
./guandan 1
作者你好，请问这个是在做什么，在windows cmd 运行不了

**Comment by AltmanD** [comment]
> ./guandan 1 作者你好，请问这个是在做什么，在windows cmd 运行不了

不支持windows环境哈，./guandan 1 意思是掼蛋游戏环境运行1局，只能在linux环境跑

**Comment by slaxman** [comment]
> > 好像没有DQNAgent这个库，能提供一份吗？我的邮箱是 [3504230@qq.com](mailto:3504230@qq.com), 非常感谢
> 
> 没有用到DQNAgent，相关代码可以注释掉

非常感谢

**Comment by SHITIANYU-hue** [comment]
请问一下现在训练的模型可以公开了吗？

**Comment by AltmanD** [comment]
> 请问一下现在训练的模型可以公开了吗？

最近实验室基于这版在做新的工作，模型公开还要再推迟一段

**Comment by lijie665** [comment]
作者你好，python不太会，我想把他接入到用java做的掼蛋游戏中，作为机器人ai出牌怎么弄，可以直接调对应接口吗

**Comment by ZzZqr** [comment]
> > 请问一下现在训练的模型可以公开了吗？
> 
> 最近实验室基于这版在做新的工作，模型公开还要再推迟一段

请问一下大佬，现在可以公布了吗

**Comment by AltmanD** [comment]
> > > 请问一下现在训练的模型可以公开了吗？
> > 
> > 
> > 最近实验室基于这版在做新的工作，模型公开还要再推迟一段
> 
> 请问一下大佬，现在可以公布了吗

模型文件到我师弟的库里下载吧 https://github.com/submit-paper/Danzero_plus/blob/main/actor_torch/q_network.ckpt ，另外他还做了增强版，效果很好

**Comment by ZzZqr** [comment]
> > > > 请问一下现在训练的模型可以公开了吗？
> > > 
> > > 
> > > 最近实验室基于这版在做新的工作，模型公开还要再推迟一段
> > 
> > 
> > 请问一下大佬，现在可以公布了吗
> 
> 模型文件到我师弟的库里下载吧 https://github.com/submit-paper/Danzero_plus/blob/main/actor_torch/q_network.ckpt ，另外他还做了增强版，效果很好

非常感谢您的回答！我想再请问一下，按照您写的配置好了tensorflow1.15，是运行start_all.sh进行训练吗？我在进行训练的时候game_out会再634行“client = MyClient(f'ws://127.0.0.1:23456/game/client{index}', args)
    client.connect()”输出ConnectionResetError: [Errno 104] Connection reset by peer，我猜想应该是因为您的代码使用了分布式的训练框架需要通过websocket来传信息，然后无法连接导致的。那如果我只有一台服务器，就没法跑起来您的训练程序了吗

**Comment by AltmanD** [comment]
> > > > > 请问一下现在训练的模型可以公开了吗？
> > > > 
> > > > 
> > > > 最近实验室基于这版在做新的工作，模型公开还要再推迟一段
> > > 
> > > 
> > > 请问一下大佬，现在可以公布了吗
> > 
> > 
> > 模型文件到我师弟的库里下载吧 https://github.com/submit-paper/Danzero_plus/blob/main/actor_torch/q_network.ckpt ，另外他还做了增强版，效果很好
> 
> 非常感谢您的回答！我想再请问一下，按照您写的配置好了tensorflow1.15，是运行start_all.sh进行训练吗？我在进行训练的时候game_out会再634行“client = MyClient(f'ws://127.0.0.1:23456/game/client{index}', args) client.connect()”输出ConnectionResetError: [Errno 104] Connection reset by peer，我猜想应该是因为您的代码使用了分布式的训练框架需要通过websocket来传信息，然后无法连接导致的。那如果我只有一台服务器，就没法跑起来您的训练程序了吗

我们的确使用了分布式训练，但是这个报错应该是因为你的掼蛋游戏程序（rl-frame/actor_n/guandan）没有启动，导致他连接不到报错的。只有一台服务器应该也是可以训练的，只不过会比较慢。现在 tensorflow1.15 已经有些过时了，建议参考师弟库里用 pytorch 吧，我们训好的模型也是可以用 pytorch 加载的。
