### ISSUE TITLE
guandan

### ISSUE THREAD

**Issue by wangdabee** [AltmanD/guandan_mcc#12]
在actor.py中，state的种类只有是str时才会给learner发送数据，但是，我看了state的种类，只有dict 或者 int.
所以actor根本不会给learner发送数据。

此外，我运行不了提供的guandan可执行文件，我是用的guandan_offline_v10062/guandan_offline_v1006/ubuntu/guandan_offline_v1006官方提供的最新版本的gamecore，请问是和这个有关系吗？谢谢。

**Comment by AltmanD** [comment]
1. 代码中state的种类并不只有dict和int，小局结束的结果是str类型
2. gamecore一直是黑盒使用，无法进行debug

**Comment by wangdabee** [comment]
您好 您使用的gamecore是guandan_offline_v10062/guandan_offline_v1006/ubuntu/guandan_offline_v1006官方提供的最新版本的gamecore吗 我运行guandan_offline_v1006 10000 和guandan_offline_v1006 1 好像都打一样的局数

**Comment by AltmanD** [comment]
v1006我这边是可以正常使用的。你描述的问题我没遇到过。
