### ISSUE TITLE
代码里Loss与论文里描述不一致，麻烦解答一下，谢谢

### ISSUE THREAD

**Issue by ZF4444** [AltmanD/guandan_mcc#2]
https://github.com/AltmanD/guandan_mcc/blob/e816ca3af431678903d051365d7c19a6dd4ebdb8/rl-frame/learner/agents/dqn/guandan_agent.py#L30

**Comment by AltmanD** [comment]
这里估计是提commit的时候不小心把错误代码交上来了，这个文件你就先使用它的上个commit吧，那个没有clip的版本也是有效果的。（或者你可以在后面乘一下q）
这里确实是我提交的时候没注意到，不好意思
