### ISSUE TITLE
吞吐量输出为0

### ISSUE THREAD

**Issue by Cyclones-Y** [AltmanD/guandan_mcc#4]
环境：
python=3.8
tensorflow=1.15.5+cu113
numpy=1.18.5
ws4py=0.5.1
pyarrow=5.0.0
pyzmq=22.3.0
## 启动命令为：
python actor_n/actor.py 
python learner/learner.py

## actor.py参数设置：
parser = ArgumentParser()
parser.add_argument('--ip', type=str, default='127.0.0.1',
                    help='IP address of learner server')
parser.add_argument('--data_port', type=int, default=5000,
                    help='Learner server port to send training data')
parser.add_argument('--param_port', type=int, default=5001,
                    help='Learner server port to subscribe model parameters')
parser.add_argument('--exp_path', type=str, default='/mnt/workspace/guandan_mcc/Clients',
                    help='Directory to save logging data, model parameters and config file')
parser.add_argument('--num_saved_ckpt', type=int, default=4,
                    help='Number of recent checkpoint files to be saved')
parser.add_argument('--observation_space', type=int, default=(567,),
                    help='The YAML configuration file')
parser.add_argument('--action_space', type=int, default=(5, 216),
                    help='The YAML configuration file')
parser.add_argument('--epsilon', type=float, default=0.01,
                    help='Epsilon')

## learner.py 参数设置：
parser = ArgumentParser()
parser.add_argument('--alg', type=str, default='MC', help='The RL algorithm')
parser.add_argument('--env', type=str, default='GuanDan', help='The game environment')
parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to receive training data')
parser.add_argument('--param_port', type=int, default=5001, help='Learner server to publish model parameters')
parser.add_argument('--model', type=str, default='guandan_model', help='Training model')
parser.add_argument('--pool_size', type=int, default=65536, help='The max length of data pool')
parser.add_argument('--batch_size', type=int, default=32768, help='The batch size for training')
parser.add_argument('--training_freq', type=int, default=250,
                    help='How many receptions of new data are between each training, '
                         'which can be fractional to represent more than one training per reception')
parser.add_argument('--keep_training', type=bool, default=False,
                    help="No matter whether new data is received recently, keep training as long as the data is enough "
                         "and ignore `--training_freq`")
parser.add_argument('--config', type=str, default=None, help='Directory to config file')
parser.add_argument('--exp_path', type=str, default=None, help='Directory to save logging data and config file')
parser.add_argument('--record_throughput_interval', type=int, default=60,
                    help='The time interval between each throughput record')
parser.add_argument('--num_envs', type=int, default=1, help='The number of environment copies')
parser.add_argument('--ckpt_save_freq', type=int, default=3000, help='The number of updates between each weights saving')
parser.add_argument('--ckpt_save_type', type=str, default='weight', help='Type of checkpoint file will be recorded : weight(smaller) or checkpoint(bigger')
parser.add_argument('--observation_space', type=int, default=(567,),
                    help='The YAML configuration file')
parser.add_argument('--action_space', type=int, default=(5, 216),
                    help='The YAML configuration file')
parser.add_argument('--epsilon', type=float, default=0.01,
                    help='Epsilon')
## 端口检测：netstat - nlt 
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5001          0.0.0.0:*               LISTEN     
tcp        0      0 10.224.128.51:10250     0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:59083         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:111           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:6000          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:6001          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:46609         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:34449         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:6002          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:6003          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:35253         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:46423         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8088            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN     
tcp        0      0 10.224.128.51:8889      0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:43713         0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:111                 :::*                    LISTEN     
tcp6       0      0 :::3011                 :::*                    LISTEN   
本地的5000，5001，6000，6001端口均已启动

启动learner.py后显示：
Logging to LEARNER-2023-11-09-17-05-31/log
Data socket has been bound to port 5000
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00
Receiving FPS: 0.00, Consuming FPS: 0.00

## 总结
依赖环境均按照项目给出的版本安装，没有对源码结构进行修改。learner.py里的参数配置均为默认值（修改过--pool_size,--batch_size的数值吞吐量打印还是为0）

**Comment by AltmanD** [comment]
按你给出的条件来看没什么问题，可以尝试检查以下部分：两个程序是否可以通过 127.0.0.1:5000 正常通信；actor.py 是否正常采集数据并发送

**Comment by youpengzhao** [comment]
请问是用docker运行的吗，我们的代码是在linux服务器上运行，actor和learner分别在不同docker里，这边设本地端口我不确定能不能运行。因为gamecore和actor交互我记得也是用的本地端口，您这样设置感觉可能是端口被占用了

**Comment by Cyclones-Y** [comment]
> 请问是用docker运行的吗，我们的代码是在linux服务器上运行，actor和learner分别在不同docker里，这边设本地端口我不确定能不能运行。因为gamecore和actor交互我记得也是用的本地端口，您这样设置感觉可能是端口被占用了

还没有使用docker,使用的是linux云服务器部署，分别启用了4个端口：5000，5001，6000，6001，ip地址换了成服务器的局域网，但是运行的时候吞吐量还是为0.

**Comment by Cyclones-Y** [comment]
> 按你给出的条件来看没什么问题，可以尝试检查以下部分：两个程序是否可以通过 127.0.0.1:5000 正常通信；actor.py 是否正常采集数据并发送

好的，我试一下

**Comment by yanzm4** [comment]
> 请问是用docker运行的吗，我们的代码是在linux服务器上运行，actor和learner分别在不同docker里，这边设本地端口我不确定能不能运行。因为gamecore和actor交互我记得也是用的本地端口，您这样设置感觉可能是端口被占用了

**Comment by lemoningi** [comment]
> 环境： python=3.8 tensorflow=1.15.5+cu113 numpy=1.18.5 ws4py=0.5.1 pyarrow=5.0.0 pyzmq=22.3.0
> 
> ## 启动命令为：
> python actor_n/actor.py python learner/learner.py
> 
> ## actor.py参数设置：
> parser = ArgumentParser() parser.add_argument('--ip', type=str, default='127.0.0.1', help='IP address of learner server') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to send training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server port to subscribe model parameters') parser.add_argument('--exp_path', type=str, default='/mnt/workspace/guandan_mcc/Clients', help='Directory to save logging data, model parameters and config file') parser.add_argument('--num_saved_ckpt', type=int, default=4, help='Number of recent checkpoint files to be saved') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> 
> ## learner.py 参数设置：
> parser = ArgumentParser() parser.add_argument('--alg', type=str, default='MC', help='The RL algorithm') parser.add_argument('--env', type=str, default='GuanDan', help='The game environment') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to receive training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server to publish model parameters') parser.add_argument('--model', type=str, default='guandan_model', help='Training model') parser.add_argument('--pool_size', type=int, default=65536, help='The max length of data pool') parser.add_argument('--batch_size', type=int, default=32768, help='The batch size for training') parser.add_argument('--training_freq', type=int, default=250, help='How many receptions of new data are between each training, ' 'which can be fractional to represent more than one training per reception') parser.add_argument('--keep_training', type=bool, default=False, help="No matter whether new data is received recently, keep training as long as the data is enough " "and ignore `--training_freq`") parser.add_argument('--config', type=str, default=None, help='Directory to config file') parser.add_argument('--exp_path', type=str, default=None, help='Directory to save logging data and config file') parser.add_argument('--record_throughput_interval', type=int, default=60, help='The time interval between each throughput record') parser.add_argument('--num_envs', type=int, default=1, help='The number of environment copies') parser.add_argument('--ckpt_save_freq', type=int, default=3000, help='The number of updates between each weights saving') parser.add_argument('--ckpt_save_type', type=str, default='weight', help='Type of checkpoint file will be recorded : weight(smaller) or checkpoint(bigger') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> 
> ## 端口检测：netstat - nlt
> Proto Recv-Q Send-Q Local Address Foreign Address State tcp 0 0 127.0.0.1:5000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:5001 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:10250 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:59083 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:111 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6001 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46609 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:34449 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6002 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8082 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6003 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:35253 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:8086 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46423 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8088 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8888 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:8889 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:43713 0.0.0.0:* LISTEN tcp6 0 0 ::1:111 :::* LISTEN tcp6 0 0 :::3011 :::* LISTEN 本地的5000，5001，6000，6001端口均已启动
> 
> 启动learner.py后显示： Logging to LEARNER-2023-11-09-17-05-31/log Data socket has been bound to port 5000 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00
> 
> ## 总结
> 依赖环境均按照项目给出的版本安装，没有对源码结构进行修改。learner.py里的参数配置均为默认值（修改过--pool_size,--batch_size的数值吞吐量打印还是为0）

我遇到了同样的问题，请问你解决了吗？谢谢

**Comment by Cyclones-Y** [comment]
> > 环境： python=3.8 tensorflow=1.15.5+cu113 numpy=1.18.5 ws4py=0.5.1 pyarrow=5.0.0 pyzmq=22.3.0
> > ## 启动命令为：
> > python actor_n/actor.py python learner/learner.py
> > ## actor.py参数设置：
> > parser = ArgumentParser() parser.add_argument('--ip', type=str, default='127.0.0.1', help='IP address of learner server') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to send training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server port to subscribe model parameters') parser.add_argument('--exp_path', type=str, default='/mnt/workspace/guandan_mcc/Clients', help='Directory to save logging data, model parameters and config file') parser.add_argument('--num_saved_ckpt', type=int, default=4, help='Number of recent checkpoint files to be saved') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> > ## learner.py 参数设置：
> > parser = ArgumentParser() parser.add_argument('--alg', type=str, default='MC', help='The RL algorithm') parser.add_argument('--env', type=str, default='GuanDan', help='The game environment') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to receive training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server to publish model parameters') parser.add_argument('--model', type=str, default='guandan_model', help='Training model') parser.add_argument('--pool_size', type=int, default=65536, help='The max length of data pool') parser.add_argument('--batch_size', type=int, default=32768, help='The batch size for training') parser.add_argument('--training_freq', type=int, default=250, help='How many receptions of new data are between each training, ' 'which can be fractional to represent more than one training per reception') parser.add_argument('--keep_training', type=bool, default=False, help="No matter whether new data is received recently, keep training as long as the data is enough " "and ignore `--training_freq`") parser.add_argument('--config', type=str, default=None, help='Directory to config file') parser.add_argument('--exp_path', type=str, default=None, help='Directory to save logging data and config file') parser.add_argument('--record_throughput_interval', type=int, default=60, help='The time interval between each throughput record') parser.add_argument('--num_envs', type=int, default=1, help='The number of environment copies') parser.add_argument('--ckpt_save_freq', type=int, default=3000, help='The number of updates between each weights saving') parser.add_argument('--ckpt_save_type', type=str, default='weight', help='Type of checkpoint file will be recorded : weight(smaller) or checkpoint(bigger') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> > ## 端口检测：netstat - nlt
> > Proto Recv-Q Send-Q Local Address Foreign Address State tcp 0 0 127.0.0.1:5000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:5001 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:10250 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:59083 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:111 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6001 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46609 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:34449 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6002 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8082 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6003 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:35253 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:8086 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46423 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8088 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8888 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:8889 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:43713 0.0.0.0:* LISTEN tcp6 0 0 ::1:111 :::* LISTEN tcp6 0 0 :::3011 :::* LISTEN 本地的5000，5001，6000，6001端口均已启动
> > 启动learner.py后显示： Logging to LEARNER-2023-11-09-17-05-31/log Data socket has been bound to port 5000 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00
> > ## 总结
> > 依赖环境均按照项目给出的版本安装，没有对源码结构进行修改。learner.py里的参数配置均为默认值（修改过--pool_size,--batch_size的数值吞吐量打印还是为0）
> 
> 我遇到了同样的问题，请问你解决了吗？谢谢
还没解决，我感觉是我自己的docker有问题，如果你有解决的办法也通知我一声，谢谢

**Comment by Cyclones-Y** [comment]
#

> > 环境： python=3.8 tensorflow=1.15.5+cu113 numpy=1.18.5 ws4py=0.5.1 pyarrow=5.0.0 pyzmq=22.3.0
> > ## 启动命令为：
> > python actor_n/actor.py python learner/learner.py
> > ## actor.py参数设置：
> > parser = ArgumentParser() parser.add_argument('--ip', type=str, default='127.0.0.1', help='IP address of learner server') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to send training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server port to subscribe model parameters') parser.add_argument('--exp_path', type=str, default='/mnt/workspace/guandan_mcc/Clients', help='Directory to save logging data, model parameters and config file') parser.add_argument('--num_saved_ckpt', type=int, default=4, help='Number of recent checkpoint files to be saved') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> > ## learner.py 参数设置：
> > parser = ArgumentParser() parser.add_argument('--alg', type=str, default='MC', help='The RL algorithm') parser.add_argument('--env', type=str, default='GuanDan', help='The game environment') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to receive training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server to publish model parameters') parser.add_argument('--model', type=str, default='guandan_model', help='Training model') parser.add_argument('--pool_size', type=int, default=65536, help='The max length of data pool') parser.add_argument('--batch_size', type=int, default=32768, help='The batch size for training') parser.add_argument('--training_freq', type=int, default=250, help='How many receptions of new data are between each training, ' 'which can be fractional to represent more than one training per reception') parser.add_argument('--keep_training', type=bool, default=False, help="No matter whether new data is received recently, keep training as long as the data is enough " "and ignore `--training_freq`") parser.add_argument('--config', type=str, default=None, help='Directory to config file') parser.add_argument('--exp_path', type=str, default=None, help='Directory to save logging data and config file') parser.add_argument('--record_throughput_interval', type=int, default=60, help='The time interval between each throughput record') parser.add_argument('--num_envs', type=int, default=1, help='The number of environment copies') parser.add_argument('--ckpt_save_freq', type=int, default=3000, help='The number of updates between each weights saving') parser.add_argument('--ckpt_save_type', type=str, default='weight', help='Type of checkpoint file will be recorded : weight(smaller) or checkpoint(bigger') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> > ## 端口检测：netstat - nlt
> > Proto Recv-Q Send-Q Local Address Foreign Address State tcp 0 0 127.0.0.1:5000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:5001 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:10250 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:59083 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:111 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6001 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46609 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:34449 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6002 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8082 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6003 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:35253 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:8086 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46423 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8088 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8888 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:8889 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:43713 0.0.0.0:* LISTEN tcp6 0 0 ::1:111 :::* LISTEN tcp6 0 0 :::3011 :::* LISTEN 本地的5000，5001，6000，6001端口均已启动
> > 启动learner.py后显示： Logging to LEARNER-2023-11-09-17-05-31/log Data socket has been bound to port 5000 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00
> > ## 总结
> > 依赖环境均按照项目给出的版本安装，没有对源码结构进行修改。learner.py里的参数配置均为默认值（修改过--pool_size,--batch_size的数值吞吐量打印还是为0）
> 
> 我遇到了同样的问题，请问你解决了吗？谢谢


还没解决，我感觉是docker的问题，应该要从docker入手，如果你有解决的办法请回复我一下，谢谢

**Comment by AltmanD** [comment]
> > > 环境： python=3.8 tensorflow=1.15.5+cu113 numpy=1.18.5 ws4py=0.5.1 pyarrow=5.0.0 pyzmq=22.3.0
> > > ## 启动命令为：
> > > python actor_n/actor.py python learner/learner.py
> > > ## actor.py参数设置：
> > > parser = ArgumentParser() parser.add_argument('--ip', type=str, default='127.0.0.1', help='IP address of learner server') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to send training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server port to subscribe model parameters') parser.add_argument('--exp_path', type=str, default='/mnt/workspace/guandan_mcc/Clients', help='Directory to save logging data, model parameters and config file') parser.add_argument('--num_saved_ckpt', type=int, default=4, help='Number of recent checkpoint files to be saved') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> > > ## learner.py 参数设置：
> > > parser = ArgumentParser() parser.add_argument('--alg', type=str, default='MC', help='The RL algorithm') parser.add_argument('--env', type=str, default='GuanDan', help='The game environment') parser.add_argument('--data_port', type=int, default=5000, help='Learner server port to receive training data') parser.add_argument('--param_port', type=int, default=5001, help='Learner server to publish model parameters') parser.add_argument('--model', type=str, default='guandan_model', help='Training model') parser.add_argument('--pool_size', type=int, default=65536, help='The max length of data pool') parser.add_argument('--batch_size', type=int, default=32768, help='The batch size for training') parser.add_argument('--training_freq', type=int, default=250, help='How many receptions of new data are between each training, ' 'which can be fractional to represent more than one training per reception') parser.add_argument('--keep_training', type=bool, default=False, help="No matter whether new data is received recently, keep training as long as the data is enough " "and ignore `--training_freq`") parser.add_argument('--config', type=str, default=None, help='Directory to config file') parser.add_argument('--exp_path', type=str, default=None, help='Directory to save logging data and config file') parser.add_argument('--record_throughput_interval', type=int, default=60, help='The time interval between each throughput record') parser.add_argument('--num_envs', type=int, default=1, help='The number of environment copies') parser.add_argument('--ckpt_save_freq', type=int, default=3000, help='The number of updates between each weights saving') parser.add_argument('--ckpt_save_type', type=str, default='weight', help='Type of checkpoint file will be recorded : weight(smaller) or checkpoint(bigger') parser.add_argument('--observation_space', type=int, default=(567,), help='The YAML configuration file') parser.add_argument('--action_space', type=int, default=(5, 216), help='The YAML configuration file') parser.add_argument('--epsilon', type=float, default=0.01, help='Epsilon')
> > > ## 端口检测：netstat - nlt
> > > Proto Recv-Q Send-Q Local Address Foreign Address State tcp 0 0 127.0.0.1:5000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:5001 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:10250 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:59083 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:111 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6000 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6001 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46609 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:34449 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6002 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8082 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:6003 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:35253 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:8086 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:46423 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8088 0.0.0.0:* LISTEN tcp 0 0 0.0.0.0:8888 0.0.0.0:* LISTEN tcp 0 0 10.224.128.51:8889 0.0.0.0:* LISTEN tcp 0 0 127.0.0.1:43713 0.0.0.0:* LISTEN tcp6 0 0 ::1:111 :::* LISTEN tcp6 0 0 :::3011 :::* LISTEN 本地的5000，5001，6000，6001端口均已启动
> > > 启动learner.py后显示： Logging to LEARNER-2023-11-09-17-05-31/log Data socket has been bound to port 5000 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00 Receiving FPS: 0.00, Consuming FPS: 0.00
> > > ## 总结
> > > 依赖环境均按照项目给出的版本安装，没有对源码结构进行修改。learner.py里的参数配置均为默认值（修改过--pool_size,--batch_size的数值吞吐量打印还是为0）
> > 
> > 
> > 我遇到了同样的问题，请问你解决了吗？谢谢
> 
> 还没解决，我感觉是docker的问题，应该要从docker入手，如果你有解决的办法请回复我一下，谢谢

按打印出的 log 来看仍需要检查两个程序（actor 和 learner）是否可以通过 127.0.0.1:5000 正常通信，可以使用 zmq 的范例程序进行简单测试一下；actor.py 是否正常采集数据并发送，可以在 actor.py 中采集数据的循环中加 print 看看是否在正常采集对局数据？
