### ISSUE TITLE
How to show the game play

### ISSUE THREAD

**Issue by StevenUST** [AltmanD/guandan_mcc#6]
I am interested in this project and I want to see four clients are playing guandan. However, how to start the game correctly as I am reading the file in showdown but which one should be executed first?

**Comment by AltmanD** [comment]
In this project, the 'showdown' module only supports monitoring one player.
For starting correctly, you can try to start without showdown module first. 'showdown' is just a GUI with socket.

**Comment by StevenUST** [comment]
> In this project, the 'showdown' module only supports monitoring one player. For starting correctly, you can try to start without showdown module first. 'showdown' is just a GUI with socket.

Now I know how to start the 23456 port and it runs correctly. However, as you mentions the showdown is just a GUI with socket, if I want to observe 4 AI players are playing and their actions are printed in the terminal which is used to execute server binary file, what are the executing steps?

**Comment by AltmanD** [comment]
As you can see, in [this file](https://github.com/AltmanD/guandan_mcc/blob/main/rl-frame/actor_n/actor.py#L197) I start 4 player, 4 socket actually. If you want to observe 4 players' actions, you can add 'print' in loop. If you need further information, [this file](https://github.com/AltmanD/guandan_mcc/blob/main/rl-frame/actor_n/game.py#L220) is where info collected, you can add whatever you want.
