### ISSUE TITLE
How to train a model

### ISSUE THREAD

**Issue by StevenUST** [AltmanD/guandan_mcc#7]
Now I can run the game in wintest file. However, I want to train a model but after executing learner.py in learner, Receiving FPS is 0.00 and Consuming FPS is also 0.0. I run actor.py first, then I run learner.py. Is something wrong with these execution steps?

**Comment by AltmanD** [comment]
You can refer to [this issue](https://github.com/AltmanD/guandan_mcc/issues/4) to check your program.

**Comment by AltmanD** [comment]
#4
