### ISSUE TITLE
请教一个逻辑问题

### ISSUE THREAD

**Issue by XliOK** [AltmanD/guandan_mcc#9]
1

**Comment by AltmanD** [comment]
理论上来说是轮不到出完牌的玩家的，裁判程序不会给出完牌的玩家发可选动作集合。这个方法中，历史出牌记录没有时间关系，只记录了出过的牌的张数，所以不用考虑出完牌的玩家。

**Comment by XliOK** [comment]
理论上不应该在历史出牌中出完牌的玩家给一个-1之类的标记吗

AltmanD ***@***.***>于2024年5月8日 周三上午10:50写道：

**Comment by AltmanD** [comment]
那确实是有的，不能跳过已出完牌的玩家时就需要填充-1

**Comment by XliOK** [comment]
所以说历史出牌如果轮到已经出完牌的玩家，是不是要加一个-1之类的标志？

AltmanD ***@***.***>于2024年5月23日 周四下午8:50写道：
